// Creature class
// Create a "bloop" creature
// NOTE: a creature is an environment


class Bloop {
  constructor(dna_, health) {
    // features
    this.name = null
    this.health = health
    this.dna = dna_
    this.attractions = [Math.random()]
    this.phenotype = { r: 0, g: 0, b: Math.round(this.attractions[0] * 100) }
    this.address = null

    // spaces
    // generated by the attached modules
    this.action_space = []
    this.observation_space = 0

    // modules
    this.slots = 4
    this.modules = []

    // state
    this.observations = []
    this.action = 0
    this.params = []
    this.state = {}
  }

  spin(observations, cost) {
    this.observations = observations
    let module = this.modules[this.action]
    let result = module.spin(this)
    // update state : add key/value of result to state object
    let newstate = Object.keys(result)
    if (newstate.length > 0) newstate.forEach(key => this.state[key] = result[key])
    this.health -= cost
    // log(`name:${this.name},action:${this.action},module:${module.constructor.name},cost:${cost},health:${this.health}`)
  }

  reset() {
    this.action = 0
    this.params = []
    this.action_space = this.modules.map((module, slot) => [slot, module.params])
    this.observations = []
  }

}

module.exports = { Bloop }